name: CI

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V27

      - name: Build
        run: nix build -L

      - uses: actions/upload-artifact@v4
        with:
          name: website
          path: result

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: website-static
          path: result

      - name: Patch
        run: |
          mv result result-old
          mkdir result
          cp -r result-old/* result
          chmod +w -R result
          echo "User-agent: *\nDisallow: /" > result/browser/robots.txt

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 2a09613716e511a8fe8ca74abc084762
          projectName: dd-ix-content
          directory: result
          gitHubToken: ${{ github.token }}
